document.writeln("<!-- 页面底部 -->");
document.writeln("    <div class=\'footer mt80\'>");
document.writeln("        <div class=\'footer-main contain clearfix\'>");
document.writeln("            <div class=\'footer-about fl\'>");
document.writeln("                <div class=\'footer-main-title\'>关于我们</div>");
document.writeln("                <div class=\'footer-about-content font14\'>");
document.writeln("                    本站图行天下图库始建于2003年，是专业的图库资源及其他设计资源服务的网站。现在已开通了设计图库、摄影图库、多媒体、字体图标、笔刷插件等多个栏目。现在设计图库栏目已经成为国内大型的同类图库站质量最高之，提供下载的文件储量达35TB以上。我们的目标是：做一个最全最好的设计资源及资源资讯网站！");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'footer-helper fl ml90\'>");
document.writeln("                <div class=\'footer-main-title\'>帮助中心</div>");
document.writeln("                <div class=\'footer-helper-content\'>");
document.writeln("                    <ul>");
document.writeln("                        <li><a href=\'\'>注册/登录</a></li>");
document.writeln("                        <li><a href=\'\'>常见问题</a></li>");
document.writeln("                        <li><a href=\'\'>版权说明</a></li>");
document.writeln("                        <li><a href=\'\'>用户协议</a></li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'footer-create fl ml90\'>");
document.writeln("                <div class=\'footer-main-title\'>创作中心</div>");
document.writeln("                <div class=\'footer-create-content\'>");
document.writeln("                    <ul>");
document.writeln("                        <li><a href=\'\'>上传图片</a></li>");
document.writeln("                        <li><a href=\'\'>签约设计师</a></li>");
document.writeln("                        <li><a href=\'\'>成为VIP</a></li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'footer-hottag fl ml90\'>");
document.writeln("                <div class=\'footer-main-title\'>热门标签</div>");
document.writeln("                <div class=\'footer-hottag-content\'>");
document.writeln("                    <ul>");
document.writeln("                        <li><a href=\'\'>创意海报</a></li>");
document.writeln("                        <li><a href=\'\'>ICON设计</a></li>");
document.writeln("                        <li><a href=\'\'>字体插件</a></li>");
document.writeln("                        <li><a href=\'\'>UI设计</a></li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'footer-customer fr\'>");
document.writeln("                <div class=\'footer-main-title\'>客服中心</div>");
document.writeln("                <div class=\'footer-customer-phone\'>");
document.writeln("                    400-810-1234");
document.writeln("                </div>");
document.writeln("                <div class=\'footer-customer-time mt15 font14\'>");
document.writeln("                    工作时间 9 : 00-18 : 00");
document.writeln("                </div>");
document.writeln("                <a href=\'\'>");
document.writeln("                    <div class=\'footer-customer-qq mt15\'>");
document.writeln("                        <img src=\'//js.photophoto.cn/web/v1/imgs/qq.png\' alt=\'\'>");
document.writeln("                        在线客服");
document.writeln("                    </div>");
document.writeln("                </a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'footer-links contain font14\'>");
document.writeln("            <div class=\'footer-links-title mt20 clearfix\'>");
document.writeln("                <div class=\'fl\'>为您推荐</div>");
document.writeln("                <div class=\'arrow-icon fl ml10\'></div>");
document.writeln("            </div>");
document.writeln("            <div class=\'footer-links-nav clearfix mt12\'>");
document.writeln("                <ul>");
document.writeln("                    <li class=\'active\'><a href=\'\'>友情链接</a></li>");
document.writeln("                    <li><a href=\'\'>热门搜索</a></li>");
document.writeln("                    <li><a href=\'\'>最新素材</a></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\'footer-links-item clearfix mt15\'>");
document.writeln("                <ul>");
document.writeln("                    <li><a href=\'\'>好123导航网</a></li>");
document.writeln("                    <li><a href=\'\'>中国品牌网</a></li>");
document.writeln("                    <li><a href=\'\'>图片大全</a></li>");
document.writeln("                    <li><a href=\'\'>CAD</a></li>");
document.writeln("                    <li><a href=\'\'>红网</a></li>");
document.writeln("                    <li><a href=\'\'>设计栈</a></li>");
document.writeln("                    <li><a href=\'\'>好123导航网</a></li>");
document.writeln("                    <li><a href=\'\'>中国品牌网</a></li>");
document.writeln("                    <li><a href=\'\'>中国品牌网</a></li>");
document.writeln("                    <li><a href=\'\'>中国品牌网</a></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'copyright-space\'></div>");
document.writeln("        <div class=\'copyright contain font12 mt12\'>");
document.writeln("            <div class=\'divider-d8 mb18\'></div>");
document.writeln("            <p>图行天下图库图片内容由用户免费分享产生，若发现您的权利被侵害，请联系photophoto.cn@163.com，我们尽快处理</p>");
document.writeln("            <p>Copyright © 2005-2019 图行天下 苏ICP备11053918号-1 网站统计 站长统计</p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <!-- 右下角固定导航 -->");
document.writeln("    <div class=\'bottom-nav clearfix\'>");
document.writeln("        <div class=\'icon-list fl\'>");
document.writeln("            <a href=\'\'>");
document.writeln("                <div class=\'icon-list-item icon-list-item1 bb\'>");
document.writeln("                    <div class=\'detail\'>意见反馈</div>");
document.writeln("                </div>");
document.writeln("            </a>");
document.writeln("            <a href=\'\'>");
document.writeln("                <div class=\'icon-list-item icon-list-item2 bb\'>");
document.writeln("                    <div class=\'detail\'>在线客服</div>");
document.writeln("                </div>");
document.writeln("            </a>");
document.writeln("            <a href=\'\'>");
document.writeln("                <div class=\'icon-list-item icon-list-item3 bb\'>");
document.writeln("                    <div class=\'detail\'>签约设计师</div>");
document.writeln("                </div>");
document.writeln("            </a>");
document.writeln("            <a href=\'#top\'>");
document.writeln("                <div class=\'icon-list-item icon-list-item4\'>");
document.writeln("                    <div class=\'detail\'>回到顶部</div>");
document.writeln("                </div>");
document.writeln("            </a>");
document.writeln("        </div>");
document.writeln("    </div>");