document.writeln("<!-- 顶部导航 -->");
document.writeln("    <div id=\'top\'></div>");
document.writeln("    <div id=\'header\' class=\'header\'>");
document.writeln("        <div class=\'header-content contain clearfix\'>");
document.writeln("            <div class=\'header-content-logo fl\'>");
document.writeln("                <a href=\'../index.html\' style=\'background: url(//js.photophoto.cn/web/v1/imgs/logo.png\') 100% no-repeat;\'></a>");
document.writeln("            </div>");
document.writeln("            <div class=\'header-content-nav\'>");
document.writeln("                <ul>");
document.writeln("                    <li class=\'active\'>");
document.writeln("                        <a href=\'\'>热门下载</a>");
document.writeln("                        <!-- 次级导航 -->");
document.writeln("                        <div class=\'secondary\'></div>");
document.writeln("                    </li>");
document.writeln("                    <li><a href=\'./secondary.html\'>平面广告</a></li>");
document.writeln("                    <li><a href=\'\'>视频/动画</a></li>");
document.writeln("                    <li><a href=\'\'>背景 /摄影</a></li>");
document.writeln("                    <li><a href=\'\'>办公素材</a></li>");
document.writeln("                    <li><a href=\'\'>样式/插件</a></li>");
document.writeln("                    <li><a href=\'\'>电商设计</a></li>");
document.writeln("                    <li><a href=\'\'>元素/插画</a></li>");
document.writeln("                    <li><a href=\'\'>UI设计</a></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\'header-content-main fl\'>");
document.writeln("                <div class=\'main-nav\'>");
document.writeln("                    作品分类");
document.writeln("                    <div class=\'main-nav-list\'>");
document.writeln("                        <ul>");
document.writeln("                            <li><a href=\'\'>平面广告</a></li>");
document.writeln("                            <li class=\'active\'><a href=\'\'>视频 / 动画</a></li>");
document.writeln("                            <li><a href=\'\'>背景 / 摄影</a></li>");
document.writeln("                            <li><a href=\'\'>办公文档</a></li>");
document.writeln("                            <li><a href=\'\'>样式 / 插件</a></li>");
document.writeln("                            <li><a href=\'\'>电商设计</a></li>");
document.writeln("                            <li><a href=\'\'>元素 / 插画</a></li>");
document.writeln("                            <li><a href=\'\'>UI设计</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'main-search mt12\'>");
document.writeln("                    <div class=\'main-search-select\'>");
document.writeln("                        <span class=\'select-text\'>全部</span>");
document.writeln("                        <span class=\'select-icon ml5\'></span>");
document.writeln("                        <div class=\'select-divider divider-vertical-e6\'></div>");
document.writeln("                        <div class=\'select-option\'>");
document.writeln("                            <ul>");
document.writeln("                                <li class=\'active\'>全部</li>");
document.writeln("                                <li>图片</li>");
document.writeln("                                <li>视频</li>");
document.writeln("                                <li>照片</li>");
document.writeln("                            </ul>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                    <input class=\'main-search-text\' type=\'text\' placeholder=\'输入关键词，素材标号搜索\'>");
document.writeln("                    <div class=\'main-search-btn\'></div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'header-content-user fr\'>");
document.writeln("                <a href=\'/\' class=\'vip-box mr15\'>");
document.writeln("                    个人VIP");
document.writeln("                </a>");
document.writeln("                <div class=\'btn-login fr mt18 font14\'>");
document.writeln("                    登录");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <!-- 登录注册 -->");
document.writeln("    <div id=\'login-box\' class=\'login\'>");
document.writeln("        <div class=\'login-box-close\'>");
document.writeln("            <i class=\'iconfont\'>&#xe607;</i>");
document.writeln("        </div>");
document.writeln("        <div class=\'login-box\'>");
document.writeln("            <div class=\'login-header clearfix\'>");
document.writeln("                <div class=\'login-header-left fl\'>");
document.writeln("                    <span class=\'login-title\'>手机登录</span>");
document.writeln("                    <span class=\'register-title\'>短信注册</span>");
document.writeln("                </div>");
document.writeln("                <div class=\'login-header-right fr\'>直接登录 <i class=\'iconfont\'>&#xe600;</i></div>");
document.writeln("            </div>");
document.writeln("            <div class=\'login-divider\'></div>");
document.writeln("            <div class=\'login-phone clearfix\'>");
document.writeln("                <div class=\'login-phone-code fl\'>");
document.writeln("                    <input id=\'login-phone-code\' type=\'text\'>");
document.writeln("                    <div class=\'code-select-icon\'><i class=\'iconfont\'>&#xe690;</i></div>");
document.writeln("                </div>");
document.writeln("                <div class=\'login-phone-number fl\'>");
document.writeln("                    <input id=\'login-phone-number\' type=\'number\' placeholder=\'输入手机号\'>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div id=\'slide\' class=\'slide mt20\'></div>");
document.writeln("            <div class=\'login-verify clearfix mt20\'>");
document.writeln("                <input id=\'login-verify-code\' type=\'text\' placeholder=\'输入验证码\'>");
document.writeln("                <div class=\'login-verify-btn btn\'>发送验证码</div>");
document.writeln("            </div>");
document.writeln("            <div class=\'login-password mt20\'>");
document.writeln("                <input id=\'login-password\' type=\'text\' placeholder=\'输入密码\'>");
document.writeln("                <div class=\'login-password-icon\'>");
document.writeln("                    <i class=\'iconfont\'>&#xe608;</i>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'login-agree\'>");
document.writeln("                <div class=\'login-agree-radio\'>");
document.writeln("                    <input id=\'agreement\' name=\'agreement\' type=\'checkbox\' hidden>");
document.writeln("                    <label for=\'agreement\' class=\'agree-radio\'></label>");
document.writeln("                    已阅读并同意<a href=\'\'>《用户协议》</a>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'login-toRegister\'>没有账号？</div>");
document.writeln("            <div class=\'register-btn btn\'>立即注册</div>");
document.writeln("            <div class=\'login-btn btn\'>登录</div>");
document.writeln("            <div class=\'third-text\'><span>第三方账号登录</span></div>");
document.writeln("        </div>");
document.writeln("        <div class=\'qrcode-box\'></div>");
document.writeln("    </div>");
document.writeln("<div id=\'mask\'></div>");